apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp
  labels:
    app: flaskapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - name: flaskapp
        image: python/flask:v2
        ports:
        - name: flaskapp-port
          containerPort: 3000


---
apiVersion: v1
kind: Service
metadata:
  name: flaskapp
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: flaskapp
  type: NodePort
