apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-website
  labels:
    app: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: webapp
#        image: webapp:1.0
        image: images6-01-23
        ports:
        - containerPort: 5000



